name:          Fireant Engineering Best Practices
title:         Fireant Engineering Best Practices
description:   Project engineering best practices used by Fireant.
url:           https://fireantstudio.github.io/Engineering-Best-Practices/
author:
  name:    Fireant
  email:   info@fireantstudio.com
  github:  Fireant
  twitter: Fireant

markdown:      redcarpet
permalink:     pretty
highlighter:   pygments
encoding:      utf-8
redcarpet:
  extensions: [with_toc_data]
sass:
  sass_dir: _includes/_sass
CONFIG:
  BASE_PATH: https://fireantstudio.github.io/Engineering-Best-Practices

  ASSET_PATH: false
